# Generated by Django 2.1.7 on 2019-06-07 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=2083)),
                ('instagram', models.CharField(max_length=2083)),
                ('twitter', models.CharField(max_length=2083)),
                ('bandcamp', models.CharField(max_length=2083)),
                ('soundcloud', models.CharField(max_length=2083)),
                ('tumblr', models.CharField(max_length=2083)),
                ('patreon', models.CharField(max_length=2083)),
                ('website', models.CharField(max_length=2083)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.artists')),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.artists')),
            ],
        ),
        migrations.CreateModel(
            name='status_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_app.status_codes'),
        ),
        migrations.AddField(
            model_name='artists',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_app.regions'),
        ),
        migrations.AddField(
            model_name='artist_tags',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.artists'),
        ),
        migrations.AddField(
            model_name='artist_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.tags'),
        ),
    ]
