# Generated by Django 2.1.7 on 2019-06-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_auto_20190607_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
