# Generated by Django 2.1.7 on 2019-06-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_auto_20190607_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artists',
            new_name='artist',
        ),
        migrations.RenameModel(
            old_name='regions',
            new_name='region',
        ),
        migrations.RenameModel(
            old_name='status_codes',
            new_name='status_code',
        ),
    ]
