# Generated by Django 2.1.7 on 2019-06-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_auto_20190607_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
