# Generated by Django 2.1.7 on 2019-06-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_auto_20190607_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
