# Generated by Django 2.1.7 on 2019-06-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0007_auto_20190608_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status_code',
            new_name='status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
