# Generated by Django 2.1.7 on 2019-06-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0008_auto_20190608_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
