# Generated by Django 2.1.7 on 2019-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
    ]
