# Generated by Django 2.1.7 on 2019-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0010_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='db_app.status'),
        ),
    ]
