# Generated by Django 2.1.7 on 2019-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0011_artist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='bandcamp',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='facebook',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='instagram',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='patreon',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='soundcloud',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='tumblr',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='twitter',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='website',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
