# Generated by Django 2.1.7 on 2019-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0012_auto_20190608_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
