# Generated by Django 2.1.7 on 2019-06-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0014_auto_20190609_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='db_app.status'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30),
        ),
    ]
